# Generated by Django 4.2.7 on 2023-11-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor_Manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPerformances',
            new_name='HistoricalPerformancesModel',
        ),
        migrations.RenameModel(
            old_name='PurchaseOrders',
            new_name='PurchaseOrdersModel',
        ),
        migrations.RenameModel(
            old_name='Vendors',
            new_name='VendorProfileModel',
        ),
    ]
